### ISSUE TITLE
The GNOME 43 runtime is no longer supported as of September 20 2023

### ISSUE THREAD

**Issue by TNTBOMBOM** [flathub/org.remmina.Remmina#207]
```
user@host:~$ flatpak update 
Looking for updates…

Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   org.remmina.Remmina

Nothing to do.

```

**Comment by HugLifeTiZ** [comment]
Is there any particular reason this uses the GNOME runtime anyways? It's a vanilla GTK3 app and doesn't seem to be interested in using GNOME-specific HIG. If you use FDO instead, you have a one year release cycle instead of six months, and twice as much time before the runtime goes EOL. I was able to make it build on FDO 23.08 with some changes. I did disable the web browser plugin, but it could be pulled back in.

**Comment by LaurentBonnaud** [comment]
The problem is still there...

**Comment by TheJanzap** [comment]
Yes, because there hasn't been a new release from upstream since the commit. I don't know the release schedule of Remmina, but this will be resolved once they publish a new version.

**Comment by HugLifeTiZ** [comment]
Runtime updates aren't meant to be tied to software releases, and given that Remmina's use case is accessing other computers over the network, kicking this can down the road and leaving users relying on network and security stacks that are no longer being updated is a **very** dangerous game.

What's more, upstream's manifest updates to GNOME 44, not the *actual current* version, GNOME 45. We're just going to end up in the same situation in a few months when GNOME 46 releases.

**Comment by myheroyuki** [comment]
> I don't know the release schedule of Remmina, but this will be resolved once they publish a new version.

There should be a new release by the end of the month. We had hoped to get one out sooner, but life and some large new features got in the way. 

> Runtime updates aren't meant to be tied to software releases

@HugLifeTiZ, do you know of a good way to perform runtime updates separately from doing a new release?  If so I'd be happy to look into it. 

> Is there any particular reason this uses the GNOME runtime anyways? 

The GNOME runtime has been used since before I began working on the project, so I do not know all of the reasons it was chosen. Some good points were brought up though, so I will do some research to see if there's any good reasons not to move away from it.

**Comment by LaurentBonnaud** [comment]
How about doing a "fake" release just for the goal of producing a newer flatpak bundle with updated dependencies?

**Comment by HugLifeTiZ** [comment]
That should not be necessary, @LaurentBonnaud.

> @HugLifeTiZ, do you know of a good way to perform runtime updates separately from doing a new release? If so I'd be happy to look into it.

Why do you think you need to do a release, @myheroyuki? This repo is the main source of truth for the package that is available from Flathub. That is to say, Flathub builds the package according to the manifest here. There are some packages that do direct uploads: Firefox and OBS come to mind. But OBS's old flathub repo is archived, and Firefox seems to have never had a repo in the flathub org. This repo is still here, which means that it is still the source of truth for Flathub's package builder.

Does your release process contain some sort of integration that pushes the current version of the manifest from the upstream repo to here? If so, there shouldn't be any harm in pushing runtime changes here first, as long as they also make it upstream.

**Comment by myheroyuki** [comment]
You're right that we can make some changes here. Right now we'd need to do a bit more than just updating to 45, as that breaks the build (Just tried, and the build failed, unfortunately).

Updating to 44 works, so as a quick fix I may just update to 44 now, and then spend more time working on getting the build to succeed for 45.

**Comment by HugLifeTiZ** [comment]
I noticed that when I tried to build against 45, too. You have to update the shared-modules so you can pull in libsoup-2.4, but then phodav breaks because it... tries to install udev rules???

Strangely enough, building against FDO 23.08 was as easy as telling it not to build the browser plugin. I think GNOME's runtime includes webkitgtk and all of its components, and webkitgtk takes a long time to build. I have some experience building webkitgtk; Geany uses FDO and some of its plugins use webkitgtk. So I might make a try at building it on FDO with the webkitgtk manifest I use for Geany.

What's the intended use case for the browser plugin anyways? Remote desktop access through web frontends? Can you combine that with things like SSH tunnels? I could definitely see a strong use case for web page access through an SSH tunnel.

**Comment by LaurentBonnaud** [comment]
Indeed :-).  Thanks for the fix!
