### ISSUE TITLE
GNOME 3.30 Runtime Now available

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.remmina.Remmina#4]
The GNOME 3.30 runtime is now available, which should have GCC 8 which I believe Remmina needs and is based on Freedesktop.org 18.08 so there should be better security support than the 3.28 and older runtimes. It'd be worth testing and updating if you can.

**Comment by antenore** [comment]
Thanks @nedrichards I'll have a look
CC: @giox069

**Comment by larchunix** [comment]
I already have a working version of Remmina using Gnome 3.30 runtime: https://gitlab.com/Remmina/Remmina/compare/master...wip%2Fflatpak%2Fgnome-sdk-3.30.

However, new runtime seems to bring regressions. I have cursor rendering issues with SPICE and RDP protocols (a square is displayed instead of a pointer). GNOME Boxes flatpak from flathub is also affected. With previous runtime this glitch does not occur.

I would like these issues to be fixed before switching to this new runtime. Unfortunately I'm too busy to investigate more on this matter for the time being.

**Comment by nedrichards** [comment]
Legitimate point, I'll try and raise that with upstream.

**Comment by nedrichards** [comment]
I've filed an upstream issue: https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/90

**Comment by larchunix** [comment]
@nedrichards Thanks !

**Comment by larchunix** [comment]
The merge request have been merged and the updated version of the SDK has reached flathub repository.

I updated Remmina's manifest accordingly in 1005203.

@nedrichards Thanks for your support.
